packages = [
  "requests",
  "pyodide-http",
  "numpy",
  "matplotlib",
  "scikit-learn",
  "scipy",
  "pandas",
  "statsmodels",
]

[files]
"main.py" = "main.py"
"stats.py" = "stats.py"
"api.py" = "api.py"
"env.py" = "env.py"
